#!/usr/bin/env python3
"""Turn results/*.json into the paper's tables and figures.

Every number in the paper comes through here.  Nothing is typed in by hand, so
re-running the experiments re-writes the paper's results, and a figure can never
drift away from the data behind it.

    python research/report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "research" / "results"
TABLES = ROOT / "paper" / "tables"
FIGURES = ROOT / "paper" / "figures"

SYNTHETIC_WARNING = (
    "% GENERATED by research/report.py - do not edit\n"
    "% SOURCE = synthetic.  These numbers verify that the harness runs; they are\n"
    "% NOT evidence about real products and must not be reported as results.\n")


def load(name: str) -> dict | None:
    path = RESULTS / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


def header(result: dict) -> str:
    if result.get("source") == "synthetic":
        return SYNTHETIC_WARNING
    return "% GENERATED by research/report.py - do not edit\n"


def _tex(text: str) -> str:
    """Escape what LaTeX would otherwise read as markup in a plain cell."""
    return (text.replace("\\", "\\textbackslash{}").replace("_", "\\_")
            .replace("%", "\\%").replace("&", "\\&"))


def latex_table(result: dict, columns: list[tuple[str, str, str]], rows: list[dict],
                caption: str, label: str) -> str:
    """columns: (key, heading, format spec)."""
    spec = "l" + "r" * (len(columns) - 1)
    out = [header(result), "\\begin{table}[t]", "\\centering",
           f"\\caption{{{caption}}}", f"\\label{{tab:{label}}}",
           f"\\begin{{tabular}}{{{spec}}}", "\\toprule",
           " & ".join(h for _, h, _ in columns) + " \\\\", "\\midrule"]
    for row in rows:
        cells = []
        for key, _, fmt in columns:
            value = row.get(key)
            cells.append("--" if value is None else format(value, fmt) if fmt else _tex(str(value)))
        out.append(" & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(out)


def write(name: str, text: str) -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / f"{name}.tex").write_text(text)
    print(f"  paper/tables/{name}.tex")


# --------------------------------------------------------------------- tables

def table_e2() -> None:
    r = load("E2")
    if not r:
        return
    rows = [{**row, "accuracy_pct": row["accuracy"] * 100,
             "proto_pct": row.get("accuracy_prototype", float("nan")) * 100} for row in r["rows"]]
    write("e2_fewshot", latex_table(
        r, [("k", "Views enrolled ($k$)", ""), ("accuracy_pct", "Nearest view (\\%)", ".1f"),
            ("proto_pct", "Mean prototype (\\%)", ".1f"), ("n_probes", "Probes", "d")], rows,
        caption=("Recognition accuracy against the number of reference views, on products "
                 "the representation never saw during training. A product is scored by "
                 "its nearest reference view (what the till does) or by the mean of its "
                 "views (a prototype classifier)."),
        label="fewshot"))


def table_e3() -> None:
    r = load("E3")
    if not r:
        return
    rows = [{**row, "accuracy_pct": row.get("accuracy", 0) * 100,
             "whitened_pct": row.get("accuracy_whitened", float("nan")) * 100}
            for row in r["rows"] if "error" not in row]
    caption = ("Backbone accuracy against inference cost per crop. Centred: the till's "
               "mean-centred cosine. Whitened: PCA-whitening fitted on the held-out "
               "products (J\\'egou and Chum, 2012).")
    if not r.get("comparable_timings", True):
        caption += " \\textbf{Timings span more than one runtime and are not comparable.}"
    write("e3_backbones", latex_table(
        r, [("backbone", "Backbone", ""), ("dim", "Dim.", "d"), ("runtime", "Runtime", ""),
            ("accuracy_pct", "Centred (\\%)", ".1f"), ("whitened_pct", "Whitened (\\%)", ".1f"),
            ("ms_per_crop", "ms / crop", ".1f")],
        rows, caption=caption, label="backbones"))


def table_e4() -> None:
    r = load("E4")
    if not r:
        return
    rows = [{**row, "accuracy_pct": row["accuracy"] * 100} for row in r["rows"]]
    write("e4_temporal", latex_table(
        r, [("frames", "Frames voted", "d"), ("accuracy_pct", "Accuracy (\\%)", ".1f"),
            ("n_scans", "Scans", "d")], rows,
        caption="Accuracy against the number of frames combined into one decision.",
        label="temporal"))


def table_e5() -> None:
    r = load("E5")
    if not r:
        return
    if r.get("insufficient_data"):
        write("e5_openset", header(r) +
              "% NOT RUN: " + r["error"].replace("\n", " ") + "\n")
        return
    names = {"max_cosine": "Nearest reference (ours)", "energy": "Energy score",
             "msp": "Max softmax probability"}
    scores = r.get("scores") or {"max_cosine": r}
    rows = [{"rule": names.get(k, k), "auroc": v["auroc"], "fpr95": v["fpr_at_95_tpr"],
             "tpr": v["tpr"], "fpr": v["fpr"]} for k, v in scores.items()]
    write("e5_openset", latex_table(
        r, [("rule", "Abstention rule", ""), ("auroc", "AUROC", ".3f"),
            ("fpr95", "FPR@95TPR", ".3f"), ("tpr", "TPR at $\\tau$", ".3f"),
            ("fpr", "FPR at $\\tau$", ".3f")], rows,
        caption=("Telling an enrolled product from one the shop does not stock, under three "
                 "abstention rules over the same similarity vectors. A closed-set classifier "
                 "cannot express this decision at all."),
        label="openset"))


def table_e6() -> None:
    r = load("E6")
    if not r:
        return
    ident = [{**row, "accuracy_pct": row["accuracy"] * 100,
              "ambiguous_pct": row["ambiguous_rate"] * 100} for row in r["identification"]]
    write("e6_fusion", latex_table(
        r, [("modalities", "Modalities", ""), ("accuracy_pct", "Accuracy (\\%)", ".1f"),
            ("ambiguous_pct", "Referred to operator (\\%)", ".1f")], ident,
        caption="What each sensing modality contributes to identification.",
        label="fusion"))

    swap = [{**row, "detected_pct": row["swaps_detected"] * 100,
             "false_pct": row["false_alarm_rate"] * 100} for row in r["item_swap"]]
    write("e6_swap", latex_table(
        r, [("k_sigma", "$k_\\sigma$", ".1f"),
            ("tolerance_1_item_g", "Tolerance, 1 item (g)", ".1f"),
            ("detected_pct", "Swaps detected (\\%)", ".1f"),
            ("false_pct", "False alarms (\\%)", ".1f")], swap,
        caption=("Item-swap detection against the weight tolerance. $k_\\sigma$ trades "
                 "security against accusing honest customers."),
        label="swap"))


def table_e9() -> None:
    """One row per public dataset and k; the datasets come from E9-<tag>.json files."""
    results = [json.loads(p.read_text()) for p in sorted(RESULTS.glob("E9*.json"))]
    if not results:
        return
    rows, openset = [], []
    for r in results:
        dataset = r["source"].split(":", 1)[-1]
        for x in r["fewshot"]:
            rows.append({"dataset": dataset, "k": x["k"], "accuracy_pct": x["accuracy"] * 100,
                         "proto_pct": x["accuracy_prototype"] * 100,
                         "n_probes": x["n_probes"], "n_skus": x["n_skus"]})
        for rule, v in (r.get("openset", {}).get("scores") or {}).items():
            openset.append({"dataset": dataset, "rule": rule, "auroc": v["auroc"],
                            "fpr95": v["fpr_at_95_tpr"], "tau": v["threshold"]})
    write("e9_public", latex_table(
        results[0],
        [("dataset", "Dataset", ""), ("k", "$k$", ""), ("n_skus", "SKUs scored", "d"),
         ("accuracy_pct", "Top-1 (\\%)", ".1f"), ("proto_pct", "Prototype (\\%)", ".1f"),
         ("n_probes", "Probes", "d")], rows,
        caption=("Few-shot accuracy on the Grocery Store dataset (whole photograph as the "
                 "crop; scored on the half of the classes held out as unseen). "
                 "\\emph{iconic}: the manufacturer image is the first reference view."),
        label="public"))
    if openset:
        write("e9_public_openset", latex_table(
            results[0],
            [("dataset", "Dataset", ""), ("rule", "Abstention rule", ""), ("auroc", "AUROC", ".3f"),
             ("fpr95", "FPR@95TPR", ".3f"), ("tau", "$\\tau$@95TPR", ".3f")], openset,
            caption="Open-set rejection on the Grocery Store dataset.", label="publicopenset"))


def table_e7() -> None:
    r = load("E7")
    if not r:
        return
    rows = [{"metric": "Baskets priced exactly right (\\%)", "value": r["exact_match_rate"] * 100},
            {"metric": "Mean absolute error (THB)", "value": r["mean_abs_error_baht"]},
            {"metric": "Worst basket error (THB)", "value": r["max_abs_error_baht"]},
            {"metric": "Mean signed error (THB)", "value": r["mean_signed_error_baht"]}]
    write("e7_basket", latex_table(
        r, [("metric", "Measure", ""), ("value", "Value", ".2f")], rows,
        caption=f"End-to-end pricing error over {r['n_baskets']} simulated baskets.",
        label="basket"))


def table_e8() -> None:
    r = load("E8")
    if not r:
        return
    retrain_h = r.get("closed_set_retrain_hours")
    rows = [{"method": "Proposed: enrol from $k$ views", "cost": r["total_seconds_estimate"] / 60.0},
            {"method": "Closed set: photograph, label, retrain",
             "cost": retrain_h * 60.0 if retrain_h else None}]
    write("e8_enrolment", latex_table(
        r, [("method", "Adding one product", ""), ("cost", "Minutes", ".1f")], rows,
        caption=("The cost of putting one new product on sale. The closed-set figure is "
                 "the team's own record of building the version~1 model, not an estimate."),
        label="enrolment"))


# -------------------------------------------------------------------- figures

def figures() -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    FIGURES.mkdir(parents=True, exist_ok=True)
    plt.rcParams.update({"figure.figsize": (4.2, 3.0), "font.size": 9,
                         "axes.spines.top": False, "axes.spines.right": False,
                         "savefig.bbox": "tight", "savefig.dpi": 200})

    r2 = load("E2")
    if r2:
        fig, ax = plt.subplots()
        ax.plot([x["k"] for x in r2["rows"]], [x["accuracy"] * 100 for x in r2["rows"]],
                marker="o", color="#0B5FFF")
        ax.set_xlabel("reference views per product ($k$)")
        ax.set_ylabel("top-1 accuracy (%)")
        ax.set_ylim(0, 101)
        ax.grid(alpha=.3)
        if r2.get("source") == "synthetic":
            ax.set_title("SYNTHETIC - harness check, not a result", fontsize=7, color="#B3261E")
        fig.savefig(FIGURES / "e2_fewshot.pdf")
        plt.close(fig)
        print("  paper/figures/e2_fewshot.pdf")

    r3 = load("E3")
    if r3:
        rows = [x for x in r3["rows"] if "error" not in x]
        fig, ax = plt.subplots()
        for x in rows:
            ax.scatter(x["ms_per_crop"], x["accuracy"] * 100, s=42, color="#0B5FFF")
            ax.annotate(x["backbone"].replace("_", " "), (x["ms_per_crop"], x["accuracy"] * 100),
                        textcoords="offset points", xytext=(6, -3), fontsize=7)
        ax.set_xlabel("inference cost (ms per crop)")
        ax.set_ylabel("top-1 accuracy (%)")
        ax.grid(alpha=.3)
        if not r3.get("comparable_timings", True):
            ax.set_title("timings not comparable across runtimes", fontsize=7, color="#B3261E")
        fig.savefig(FIGURES / "e3_backbones.pdf")
        plt.close(fig)
        print("  paper/figures/e3_backbones.pdf")

    r6 = load("E6")
    if r6:
        fig, ax = plt.subplots()
        rows = r6["item_swap"]
        ax.plot([x["tolerance_1_item_g"] for x in rows],
                [x["swaps_detected"] * 100 for x in rows], marker="o",
                color="#0B5FFF", label="swaps detected")
        ax.plot([x["tolerance_1_item_g"] for x in rows],
                [x["false_alarm_rate"] * 100 for x in rows], marker="s",
                color="#B3261E", label="false alarms")
        ax.set_xlabel("weight tolerance for a one-item basket (g)")
        ax.set_ylabel("%")
        ax.legend(frameon=False)
        ax.grid(alpha=.3)
        fig.savefig(FIGURES / "e6_swap.pdf")
        plt.close(fig)
        print("  paper/figures/e6_swap.pdf")


def main() -> int:
    if not RESULTS.exists():
        print("no results yet - run:  python research/run.py")
        return 1
    sources = {json.loads(p.read_text()).get("source") for p in RESULTS.glob("*.json")}
    print(f"regenerating from results in {sources}\n")
    for fn in (table_e2, table_e3, table_e4, table_e5, table_e6, table_e7, table_e8, table_e9):
        fn()
    figures()
    if "synthetic" in sources:
        print("\n  NOTE: some results are synthetic. Every generated file says so at the top.")
        print("  Real numbers need a capture session: python research/capture.py --help")
    return 0


if __name__ == "__main__":
    sys.exit(main())
